In [59]:
import numpy as np

In [60]:
inputs=[1,2,3,2.5]#the shape(1,4)

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]
output=np.dot(weights,inputs)+biases
print(output)


[4.8   1.21  2.385]


In [61]:
####idea of batches of data


In [62]:
inputs=[[1,2,3,2.5],
       [5.0,2.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
        

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+biases

print(output)

[[4.8   1.21  2.385]
 [7.1   2.42  0.23 ]
 [1.41  1.051 0.026]]


In [63]:
#adding another weight

In [64]:
inputs=[[1,2,3,2.5],
       [5.0,2.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
        

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

weights1=[[0.1,-0.14,0.5],
        [-0.5,0.12,-0.33],
        [-0.44,0.73,-0.13]]

biases2=[-1,2,-0.5]

Layer_1_output=np.dot(inputs,np.array(weights).T)+biases
Layer_2_output=np.dot(Layer_1_output,np.array(weights1).T)+biases2
print(Layer_1_output)
print('\n')
print(Layer_2_output)

[[4.8   1.21  2.385]
 [7.1   2.42  0.23 ]
 [1.41  1.051 0.026]]


[[ 0.5031  -1.04185 -2.03875]
 [-0.5138  -1.3355  -1.8873 ]
 [-0.99314  1.41254 -0.35655]]


In [65]:
#moving to object oriented programming in python

In [75]:
import numpy as np
np.random.seed(0)


X=[[1,2,3,2.5],
       [5.0,2.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

class layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.n_weights=0.01*np.random.randn(n_inputs,n_neurons)
        print("self.n_weights")
        print(self.n_weights)
        self.n_biases=np.zeros((1,n_neurons))
        print("self.n_biases")
        print(self.n_biases)
    def forward(self,inputs):
        self.output=np.dot(inputs,self.n_weights)+self.n_biases
        
            
layer1=layer_dense(4,5)
layer2=layer_dense(5,2)
layer1.forward(X)
print(layer1.output)
print('\n')
layer2.forward(layer1.output)
print(layer2.output)

        
        
        
        

self.n_weights
[[ 0.01764052  0.00400157  0.00978738  0.02240893  0.01867558]
 [-0.00977278  0.00950088 -0.00151357 -0.00103219  0.00410599]
 [ 0.00144044  0.01454274  0.00761038  0.00121675  0.00443863]
 [ 0.00333674  0.01494079 -0.00205158  0.00313068 -0.00854096]]
self.n_biases
[[0. 0. 0. 0. 0.]]
self.n_weights
[[-0.0255299   0.00653619]
 [ 0.00864436 -0.00742165]
 [ 0.02269755 -0.01454366]
 [ 0.00045759 -0.00187184]
 [ 0.01532779  0.01469359]]
self.n_biases
[[0. 0.]]
[[ 0.01075813  0.10398352  0.02446241  0.0318215   0.01885105]
 [ 0.07389011  0.05434848  0.03419621  0.11502489  0.08006932]
 [-0.05076324  0.05568842  0.0079878  -0.03488957  0.00455304]]


[[ 0.00148296 -0.00083976]
 [ 0.00063949  0.00054346]
 [ 0.0020125  -0.00072906]]


In [ ]:
#########ACTIVATION FUNCTIONS

In [ ]:
##RECTIFIED LINEAR(RELU FUNCTION)

In [76]:
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]
for i in inputs:
    if i>0:
        output.append(i)
    if i<=0:
        output.append(0)
        
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [78]:
#ANOTHER WAY TO DO IT
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]
for i in inputs:
        output.append(max(0,i));
print(output) 

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [84]:
##RELU OBJECT

inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]

class Activation_ReLU:
    def foward(self,inputs):
        self.output=np.maximum(0,inputs)


In [85]:
pip install nnfs


Note: you may need to restart the kernel to use updated packages.
